### ISSUE TITLE
Missing black background for visible channel mesoscale images

### ISSUE THREAD

**Issue by hdoverobinson** [pietern/goestools#12]
Visible channel mesoscale imagery showing the edge of the Earth disk is not given a black background as with full disks imagery. Example: https://www.dropbox.com/s/q8vbqglyg0xeeeb/OR_ABI-L2-CMIPM2-M3CFC_G16_s20181362046598_e20181362047067_c20181362047103.png?dl=0

**Comment by pietern** [comment]
That is a stunning image!

I'll take a look, should be a one line change.
