### ISSUE TITLE
How to get the 10848 x 10848 px images?

### ISSUE THREAD

**Issue by ghulands** [pietern/goestools#140]
Hi,
On the [NOAA website](https://www.star.nesdis.noaa.gov/GOES/fulldisk.php?sat=G17) they offer images at 10848 pixels. I'm wanting to find out if it's possible for goestools to fetch these?
Thanks,
Greg

**Comment by pietern** [comment]
The resolution broadcast over HRIT is 5424x5424.

If you want to receive higher resolution imagery yourself, you'll have to setup a GRB receiving station.
