### ISSUE TITLE
fatal error: proj_api.h: No such file or directory when building goestools under Ubuntu 22.04

### ISSUE THREAD

**Issue by cosmopotamian** [pietern/goestools#142]
sudo make install

[  0%] Building CXX object src/util/CMakeFiles/util.dir/fs.cc.o
[  1%] Building CXX object src/util/CMakeFiles/util.dir/string.cc.o
[  1%] Building CXX object src/util/CMakeFiles/util.dir/time.cc.o
[  1%] Linking CXX static library libutil.a
[  1%] Built target util
[  2%] Building CXX object src/lib/CMakeFiles/dir.dir/dir.cc.o
[  2%] Linking CXX static library libdir.a
[  2%] Built target dir
[  2%] Building CXX object src/lib/CMakeFiles/zip.dir/zip.cc.o
[  3%] Linking CXX static library libzip.a
[  3%] Built target zip
[  4%] Building CXX object src/lib/CMakeFiles/timer.dir/timer.cc.o
[  4%] Linking CXX static library libtimer.a
[  4%] Built target timer
[  4%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/ep.c.o
[  4%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/global.c.o
[  5%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/pipe.c.o
[  5%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/poll.c.o
[  5%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/sock.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/sockbase.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/symbol.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/ctx.c.o
[  8%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/fsm.c.o
[  8%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/pool.c.o
[  9%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/timer.c.o
[  9%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/timerset.c.o
[  9%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/usock.c.o
[ 10%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/worker.c.o
[ 10%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/alloc.c.o
[ 10%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/atomic.c.o
[ 11%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/chunk.c.o
[ 11%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/chunkref.c.o
[ 11%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/clock.c.o
[ 13%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/closefd.c.o
[ 13%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/efd.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/err.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/hash.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/list.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/msg.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/condvar.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/mutex.c.o
[ 16%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/once.c.o
[ 16%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/queue.c.o
[ 16%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/random.c.o
[ 17%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/sem.c.o
[ 17%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/sleep.c.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strcasecmp.c.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strcasestr.c.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strncasecmp.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/thread.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/wire.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/devices/device.c.o
[ 21%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/dist.c.o
[ 21%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/excl.c.o
[ 21%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/fq.c.o
[ 22%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/lb.c.o
[ 22%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/priolist.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/bus/bus.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/bus/xbus.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/push.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/pull.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/xpull.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/xpush.c.o
[ 26%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pair/pair.c.o
[ 26%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pair/xpair.c.o
[ 26%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/pub.c.o
[ 27%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/sub.c.o
[ 27%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/trie.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/xpub.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/xsub.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/req.c.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/rep.c.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/task.c.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/xrep.c.o
[ 30%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/xreq.c.o
[ 30%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/respondent.c.o
[ 30%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/surveyor.c.o
[ 32%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/xrespondent.c.o
[ 32%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/xsurveyor.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/backoff.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/dns.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/iface.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/literal.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/port.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/streamhdr.c.o
[ 35%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/base64.c.o
[ 35%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/binproc.c.o
[ 35%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/cinproc.c.o
[ 36%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/inproc.c.o
[ 36%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/ins.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/msgqueue.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/sinproc.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/aipc.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/bipc.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/cipc.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/ipc.c.o
[ 40%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/sipc.c.o
[ 40%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/atcp.c.o
[ 40%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/btcp.c.o
[ 41%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/ctcp.c.o
[ 41%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/stcp.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/tcp.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/aws.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/bws.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/cws.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/sws.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/ws.c.o
[ 45%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/ws_handshake.c.o
[ 45%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/sha1.c.o
[ 45%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/poller.c.o
In file included from /home/engineering/Documents/goestools/vendor/nanomsg/src/aio/poller.c:27:
/home/engineering/Documents/goestools/vendor/nanomsg/src/aio/poller_epoll.inc: In function ‘nn_poller_add’:
/home/engineering/Documents/goestools/vendor/nanomsg/src/aio/poller_epoll.inc:64:9: warning: unused variable ‘rc’ [-Wunused-variable]
   64 |     int rc;
      |         ^~
[ 46%] Linking C static library ../libnanomsg.a
[ 46%] Built target nanomsg
[ 46%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/packet_reader.cc.o
[ 46%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/nanomsg_reader.cc.o
[ 47%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/file_reader.cc.o
[ 47%] Linking CXX static library libpacket_reader.a
[ 47%] Built target packet_reader
[ 47%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/packet_writer.cc.o
[ 48%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/nanomsg_writer.cc.o
[ 48%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/file_writer.cc.o
[ 48%] Linking CXX static library libpacket_writer.a
[ 48%] Built target packet_writer
[ 50%] Building CXX object src/lib/CMakeFiles/unzip.dir/unzip.cc.o
[ 50%] Linking CXX executable unzip
[ 50%] Built target unzip
[ 50%] Building CXX object src/lib/CMakeFiles/version.dir/version.cc.o
[ 51%] Linking CXX static library libversion.a
[ 51%] Built target version
[ 52%] Building CXX object src/lrit/CMakeFiles/lrit.dir/lrit.cc.o
[ 52%] Building CXX object src/lrit/CMakeFiles/lrit.dir/file.cc.o
[ 52%] Building CXX object src/lrit/CMakeFiles/lrit.dir/json.cc.o
[ 53%] Linking CXX static library liblrit.a
[ 53%] Built target lrit
[ 53%] Building CXX object src/lrit/CMakeFiles/lritdump.dir/lritdump.cc.o
[ 54%] Linking CXX executable lritdump
[ 54%] Built target lritdump
[ 55%] Building CXX object src/lrit/CMakeFiles/areadump.dir/areadump.cc.o
[ 55%] Linking CXX executable areadump
[ 55%] Built target areadump
[ 55%] Building CXX object src/dcs/CMakeFiles/dcs.dir/dcs.cc.o
[ 57%] Linking CXX static library libdcs.a
[ 57%] Built target dcs
[ 57%] Building CXX object src/dcs/CMakeFiles/dcsdump.dir/dcsdump.cc.o
[ 57%] Linking CXX executable dcsdump
[ 57%] Built target dcsdump
[ 58%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/polynomial.c.o
[ 58%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/reed-solomon.c.o
[ 58%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/encode.c.o
[ 59%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/decode.c.o
[ 59%] Built target correct-reed-solomon
[ 59%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/bit.c.o
[ 60%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/metric.c.o
[ 60%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/history_buffer.c.o
/home/engineering/Documents/goestools/vendor/libcorrect/src/convolutional/history_buffer.c: In function ‘history_buffer_search’:
/home/engineering/Documents/goestools/vendor/libcorrect/src/convolutional/history_buffer.c:57:12: warning: ‘bestpath’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   57 |     return bestpath;
      |            ^~~~~~~~
[ 60%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/error_buffer.c.o
[ 61%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/lookup.c.o
[ 61%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/convolutional.c.o
[ 61%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/encode.c.o
[ 63%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/decode.c.o
[ 63%] Built target correct-convolutional
[ 63%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/lookup.c.o
[ 64%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/convolutional.c.o
[ 64%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/encode.c.o
[ 64%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/decode.c.o
[ 64%] Built target correct-convolutional-sse
[ 64%] Linking C static library lib/libcorrect.a
[ 64%] Built target correct_static
[ 65%] Building CXX object src/decoder/CMakeFiles/compute_sync_words.dir/compute_sync_words.cc.o
[ 65%] Linking CXX executable compute_sync_words
[ 65%] Built target compute_sync_words
[ 65%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/correlator.cc.o
[ 66%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/derandomizer.cc.o
[ 66%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/packetizer.cc.o
[ 66%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/reader.cc.o
[ 67%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/reed_solomon.cc.o
[ 67%] Linking CXX static library libpacketizer.a
[ 67%] Built target packetizer
[ 69%] Building CXX object src/decoder/CMakeFiles/packetdump.dir/packetdump.cc.o
[ 69%] Linking CXX executable packetdump
[ 69%] Built target packetdump
[ 70%] Building CXX object src/assembler/CMakeFiles/packetinfo.dir/packetinfo.cc.o
[ 70%] Linking CXX executable packetinfo
[ 70%] Built target packetinfo
[ 70%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/encode.c.o
[ 70%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/encode_accessors.c.o
[ 71%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/decode.c.o
[ 71%] Linking C static library libaec.a
[ 71%] Built target aec
[ 71%] Building C object vendor/libaec/src/CMakeFiles/sz.dir/sz_compat.c.o
[ 71%] Linking C static library libsz.a
[ 71%] Built target sz
[ 71%] Building CXX object src/assembler/CMakeFiles/assembler.dir/assembler.cc.o
[ 72%] Building CXX object src/assembler/CMakeFiles/assembler.dir/crc.cc.o
[ 72%] Building CXX object src/assembler/CMakeFiles/assembler.dir/session_pdu.cc.o
[ 72%] Building CXX object src/assembler/CMakeFiles/assembler.dir/transport_pdu.cc.o
[ 73%] Building CXX object src/assembler/CMakeFiles/assembler.dir/virtual_channel.cc.o
[ 73%] Linking CXX static library libassembler.a
[ 73%] Built target assembler
[ 73%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/packet_publisher.cc.o
[ 75%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/publisher.cc.o
[ 75%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/sample_publisher.cc.o
[ 76%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/soft_bit_publisher.cc.o
[ 76%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/stats_publisher.cc.o
[ 76%] Linking CXX static library libpublisher.a
[ 76%] Built target publisher
[ 77%] Building CXX object src/goesrecv/CMakeFiles/airspy_source.dir/airspy_source.cc.o
[ 77%] Linking CXX static library libairspy_source.a
[ 77%] Built target airspy_source
[ 77%] Building CXX object src/goesrecv/CMakeFiles/rtlsdr_source.dir/rtlsdr_source.cc.o
[ 78%] Linking CXX static library librtlsdr_source.a
[ 78%] Built target rtlsdr_source
[ 78%] Building CXX object src/goesrecv/CMakeFiles/nanomsg_source.dir/nanomsg_source.cc.o
[ 79%] Linking CXX static library libnanomsg_source.a
[ 79%] Built target nanomsg_source
[ 79%] Building CXX object src/goesrecv/CMakeFiles/agc.dir/agc.cc.o
[ 79%] Linking CXX static library libagc.a
[ 79%] Built target agc
[ 79%] Building CXX object src/goesrecv/CMakeFiles/rrc.dir/rrc.cc.o
[ 79%] Linking CXX static library librrc.a
[ 79%] Built target rrc
[ 79%] Building CXX object src/goesrecv/CMakeFiles/costas.dir/costas.cc.o
[ 80%] Linking CXX static library libcostas.a
[ 80%] Built target costas
[ 82%] Building CXX object src/goesrecv/CMakeFiles/clock_recovery.dir/clock_recovery.cc.o
[ 82%] Linking CXX static library libclock_recovery.a
[ 82%] Built target clock_recovery
[ 83%] Building CXX object src/goesrecv/CMakeFiles/quantize.dir/quantize.cc.o
[ 83%] Linking CXX static library libquantize.a
[ 83%] Built target quantize
[ 83%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/goesrecv.cc.o
[ 84%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/config.cc.o
[ 84%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/options.cc.o
[ 85%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/decoder.cc.o
[ 85%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/demodulator.cc.o
[ 85%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/monitor.cc.o
[ 86%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/datagram_socket.cc.o
[ 86%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/source.cc.o
[ 86%] Linking CXX executable goesrecv
[ 86%] Built target goesrecv
[ 86%] Building CXX object src/goesrecv/CMakeFiles/benchmark.dir/benchmark.cc.o
[ 88%] Linking CXX executable benchmark
[ 88%] Built target benchmark
[ 89%] Building CXX object src/goeslrit/CMakeFiles/goeslrit.dir/goeslrit.cc.o
[ 89%] Building CXX object src/goeslrit/CMakeFiles/goeslrit.dir/options.cc.o
[ 89%] Linking CXX executable goeslrit
[ 89%] Built target goeslrit
[ 90%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/area.cc.o
[ 90%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/config.cc.o
[ 91%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/filename.cc.o
[ 91%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/file_writer.cc.o
[ 91%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/goesproc.cc.o
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/gradient.cc.o
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/handler_emwin.cc.o
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/handler_goesn.cc.o
In file included from /home/engineering/Documents/goestools/src/goesproc/map_drawer.h:5,
                 from /home/engineering/Documents/goestools/src/goesproc/handler_goesn.cc:12:
/home/engineering/Documents/goestools/src/goesproc/proj.h:16:10: fatal error: proj_api.h: No such file or directory
   16 | #include <proj_api.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/goesproc/CMakeFiles/goesproc.dir/build.make:174: src/goesproc/CMakeFiles/goesproc.dir/handler_goesn.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2398: src/goesproc/CMakeFiles/goesproc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by x31415926** [comment]
I don't know this is the best way to fix it since I'd expect both version will need to coexist for a while. So I'd defer to the repository owner on whether this is ideal or not. On top of it, my testing was limited, but here's the patch diff I used in case someone else wants to try it out.
[proj8.patch.zip](https://github.com/pietern/goestools/files/8748982/proj8.patch.zip)

**Comment by twcutter** [comment]
I'm assuming you are using debian? The current version of MIT's PROJ library is 9.0.0[(https://proj.org) which is not backward compatible.  The last version which had the proj_api.h was probably PROJ.4 of libproj-dev found in buster release.  (https://packages.debian.org/buster/amd64/libproj-dev/filelist)   You might want to get the older library and remove the latest?

**Comment by twcutter** [comment]
Now that I'm paying more attention .. ubuntu.. it appears in the bionic (18.04) release to be present which was libproj-dev  bionic, not in Jammy (22.04).

**Comment by x31415926** [comment]
I am not sure who this question was addressed to (me or the issue creator), but, yes, the issue has to do with proj library no longer supporting a backward compatibility facility which enabled goestool to continue building on Debian. This manifests in most recent Ubuntu releases today and, at some point, will for other distros. The proj deprecation was on schedule for a while and the patch above tries to deal with the somewhat minimal changes required to port it to the most recent version.

**Comment by gvfd107** [comment]
Same issue here for me, i tried deleting the dependencies for proj_api.h and resulted in many more fatal errors for the "Make" step. will revert back to Bionic until we can figure this out.

**Comment by pietern** [comment]
This was fixed in #148 and #167. Thanks for reporting.
