### ISSUE TITLE
Error: no configuration file specified

### ISSUE THREAD

**Issue by Hellmanx** [pietern/goestools#144]
So, I'm just trying to see what my signal is like, and I am not able to execute: `goesrecv -v -i 1` and I get the error:
`goesrecv: no configuration file specified
Try 'goesrecv --help' for more information.`

The documentation does not specify any specific location for the config.  Nor can I find it myself.

Am I missing something??

**Comment by pietern** [comment]
You can find an example configuration here: https://github.com/pietern/goestools/blob/main/etc/goesrecv.conf

Make sure to uncomment the lines that apply (e.g. `mode = "hrit"`, the type of receiver, etc).
