### ISSUE TITLE
Raspberry pi3 install not working

### ISSUE THREAD

**Issue by datatechnician63** [pietern/goestools#147]
Been trying to get this to work,but when I get to 
goesrecv -v -i 1 -c ~/goesrecv.conf 

I get illegal operation
I verified sudo nano goesrecv.conf has correct entries
rtl_test output works 
Not sure what to check, thanks

**Comment by pietern** [comment]
Could you share the output of CMake, the compilation step, as well as the full error you see on running goesrecv?
