### ISSUE TITLE
Reading packets from a publisher (how to)

### ISSUE THREAD

**Issue by Mopar44084** [pietern/goestools#157]
I was wondering how to send images to another PC? I would like to free up some clu usage on the pi as I'm running 73 python scripts to send images to my discord server. 
 I don't understand what command I need or how to setup the other computer.

Thanks a lot!

**Comment by pietern** [comment]
You can choose to run `goesproc` (the process that turns the raw data packets into images) on a different machine. Then instead of pointing it at `localhost` in the `--subscribe` argument, you specify the IP of the machine running `goesrecv`, e.g. `--subscribe tcp://<IP of RPi>:5004`.

Good luck!
