### ISSUE TITLE
Handle non-CMIP products from GOES-R series

### ISSUE THREAD

**Issue by pietern** [pietern/goestools#16]
Looks like there are some experiments going on sending products other than the Cloud and Moisture Image Product on the HRIT stream. The goesproc handler only deals with the CMIP product and expects details to be embedded in the LRIT ancillary text header and this is missing from the new files.

There should be a separate handler for non-CMIP products.

**Comment by elafargue** [comment]
Looks like this is handled now ?

**Comment by pietern** [comment]
Indeed! Thanks, @elafargue. Closing the issue.
