### ISSUE TITLE
fatal error: proj_api.h: No such file or directory Ubuntu server 22.04 LTS

### ISSUE THREAD

**Issue by WakeUpWolfgang** [pietern/goestools#160]
I am trying to build goestools on Ubuntu server 22.04 but I keep getting "fatal error: proj_api.h: No such file or directory"
`matt@sat:~/goestools/build$ sudo make -j2 install
[  1%] Building CXX object src/util/CMakeFiles/util.dir/fs.cc.o
[  1%] Building CXX object src/lib/CMakeFiles/dir.dir/dir.cc.o
[  2%] Building CXX object src/util/CMakeFiles/util.dir/string.cc.o
[  2%] Linking CXX static library libdir.a
[  2%] Built target dir
[  2%] Building CXX object src/lib/CMakeFiles/zip.dir/zip.cc.o
[  2%] Building CXX object src/util/CMakeFiles/util.dir/time.cc.o
[  3%] Linking CXX static library libzip.a
[  3%] Built target zip
[  4%] Building CXX object src/lib/CMakeFiles/timer.dir/timer.cc.o
[  4%] Linking CXX static library libutil.a
[  4%] Built target util
[  4%] Linking CXX static library libtimer.a
[  4%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/ep.c.o
[  4%] Built target timer
[  5%] Building CXX object src/lib/CMakeFiles/unzip.dir/unzip.cc.o
[  5%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/global.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/pipe.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/poll.c.o
[  7%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/sock.c.o
[  7%] Linking CXX executable unzip
[  7%] Built target unzip
[  7%] Building CXX object src/lib/CMakeFiles/version.dir/version.cc.o
[  8%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/sockbase.c.o
[  8%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/core/symbol.c.o
[  8%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/ctx.c.o
[  9%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/fsm.c.o
[  9%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/pool.c.o
[ 10%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/timer.c.o
[ 11%] Linking CXX static library libversion.a
[ 11%] Built target version
[ 13%] Building CXX object src/lrit/CMakeFiles/lrit.dir/lrit.cc.o
[ 13%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/timerset.c.o
[ 13%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/usock.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/worker.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/alloc.c.o
[ 14%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/atomic.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/chunk.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/chunkref.c.o
[ 15%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/clock.c.o
[ 16%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/closefd.c.o
[ 16%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/efd.c.o
[ 17%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/err.c.o
[ 17%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/hash.c.o
[ 17%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/list.c.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/msg.c.o
[ 19%] Building CXX object src/lrit/CMakeFiles/lrit.dir/file.cc.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/condvar.c.o
[ 19%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/mutex.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/once.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/queue.c.o
[ 20%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/random.c.o
[ 21%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/sem.c.o
[ 21%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/sleep.c.o
[ 22%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strcasecmp.c.o
[ 22%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strcasestr.c.o
[ 22%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/strncasecmp.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/thread.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/utils/wire.c.o
[ 23%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/devices/device.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/dist.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/excl.c.o
[ 25%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/fq.c.o
[ 26%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/lb.c.o
[ 26%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/utils/priolist.c.o
[ 27%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/bus/bus.c.o
[ 27%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/bus/xbus.c.o
[ 27%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/push.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/pull.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/xpull.c.o
[ 28%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pipeline/xpush.c.o
[ 28%] Building CXX object src/lrit/CMakeFiles/lrit.dir/json.cc.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pair/pair.c.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pair/xpair.c.o
[ 29%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/pub.c.o
[ 30%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/sub.c.o
[ 30%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/trie.c.o
[ 32%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/xpub.c.o
[ 32%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/pubsub/xsub.c.o
[ 32%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/req.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/rep.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/task.c.o
[ 33%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/xrep.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/reqrep/xreq.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/respondent.c.o
[ 34%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/surveyor.c.o
[ 35%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/xrespondent.c.o
[ 35%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/protocols/survey/xsurveyor.c.o
[ 36%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/backoff.c.o
[ 36%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/dns.c.o
[ 36%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/iface.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/literal.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/port.c.o
[ 38%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/streamhdr.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/utils/base64.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/binproc.c.o
[ 39%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/cinproc.c.o
[ 40%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/inproc.c.o
[ 40%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/ins.c.o
[ 41%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/msgqueue.c.o
[ 41%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/inproc/sinproc.c.o
[ 41%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/aipc.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/bipc.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/cipc.c.o
[ 42%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/ipc.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ipc/sipc.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/atcp.c.o
[ 44%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/btcp.c.o
[ 45%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/ctcp.c.o
[ 45%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/stcp.c.o
[ 46%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/tcp/tcp.c.o
[ 46%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/aws.c.o
[ 46%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/bws.c.o
[ 47%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/cws.c.o
[ 47%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/sws.c.o
[ 47%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/ws.c.o
[ 48%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/ws_handshake.c.o
[ 48%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/transports/ws/sha1.c.o
[ 48%] Building C object vendor/nanomsg/src/CMakeFiles/nanomsg.dir/aio/poller.c.o
In file included from /home/matt/goestools/vendor/nanomsg/src/aio/poller.c:27:
/home/matt/goestools/vendor/nanomsg/src/aio/poller_epoll.inc: In function ‘nn_poller_add’:
/home/matt/goestools/vendor/nanomsg/src/aio/poller_epoll.inc:64:9: warning: unused variable ‘rc’ [-Wunused-variable]
   64 |     int rc;
      |         ^~
[ 50%] Linking C static library ../libnanomsg.a
[ 50%] Built target nanomsg
[ 50%] Building CXX object src/dcs/CMakeFiles/dcs.dir/dcs.cc.o
[ 51%] Linking CXX static library libdcs.a
[ 51%] Built target dcs
[ 52%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/polynomial.c.o
[ 52%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/reed-solomon.c.o
[ 52%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/encode.c.o
[ 53%] Building C object vendor/libcorrect/src/reed-solomon/CMakeFiles/correct-reed-solomon.dir/decode.c.o
[ 54%] Linking CXX static library liblrit.a
[ 54%] Built target correct-reed-solomon
[ 54%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/bit.c.o
[ 55%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/metric.c.o
[ 55%] Built target lrit
[ 55%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/history_buffer.c.o
[ 55%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/lookup.c.o
/home/matt/goestools/vendor/libcorrect/src/convolutional/history_buffer.c: In function ‘history_buffer_search’:
/home/matt/goestools/vendor/libcorrect/src/convolutional/history_buffer.c:57:12: warning: ‘bestpath’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   57 |     return bestpath;
      |            ^~~~~~~~
[ 55%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/error_buffer.c.o
[ 57%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/lookup.c.o
[ 57%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/convolutional.c.o
[ 57%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/encode.c.o
[ 58%] Building C object vendor/libcorrect/src/convolutional/CMakeFiles/correct-convolutional.dir/decode.c.o
[ 59%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/convolutional.c.o
[ 59%] Built target correct-convolutional
[ 60%] Building CXX object src/assembler/CMakeFiles/packetinfo.dir/packetinfo.cc.o
[ 60%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/encode.c.o
[ 60%] Linking CXX executable packetinfo
[ 60%] Built target packetinfo
[ 60%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/encode.c.o
[ 60%] Building C object vendor/libcorrect/src/convolutional/sse/CMakeFiles/correct-convolutional-sse.dir/decode.c.o
[ 60%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/encode_accessors.c.o
[ 61%] Building C object vendor/libaec/src/CMakeFiles/aec.dir/decode.c.o
[ 61%] Built target correct-convolutional-sse
[ 61%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/packet_publisher.cc.o
[ 61%] Linking C static library libaec.a
[ 61%] Built target aec
[ 61%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/packet_reader.cc.o
[ 61%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/nanomsg_reader.cc.o
[ 63%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/publisher.cc.o
[ 64%] Building CXX object src/lib/CMakeFiles/packet_reader.dir/file_reader.cc.o
[ 64%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/sample_publisher.cc.o
[ 64%] Linking CXX static library libpacket_reader.a
[ 64%] Built target packet_reader
[ 64%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/packet_writer.cc.o
[ 65%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/nanomsg_writer.cc.o
[ 66%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/soft_bit_publisher.cc.o
[ 66%] Building CXX object src/lib/CMakeFiles/packet_writer.dir/file_writer.cc.o
[ 66%] Linking CXX static library libpacket_writer.a
[ 66%] Built target packet_writer
[ 66%] Building CXX object src/lrit/CMakeFiles/lritdump.dir/lritdump.cc.o
[ 66%] Building CXX object src/goesrecv/CMakeFiles/publisher.dir/stats_publisher.cc.o
[ 66%] Linking CXX static library libpublisher.a
[ 66%] Built target publisher
[ 67%] Building CXX object src/lrit/CMakeFiles/areadump.dir/areadump.cc.o
[ 67%] Linking CXX executable areadump
[ 67%] Built target areadump
[ 67%] Building CXX object src/dcs/CMakeFiles/dcsdump.dir/dcsdump.cc.o
[ 69%] Linking CXX executable lritdump
[ 69%] Built target lritdump
[ 69%] Linking C static library lib/libcorrect.a
[ 69%] Built target correct_static
[ 69%] Building C object vendor/libaec/src/CMakeFiles/sz.dir/sz_compat.c.o
[ 69%] Linking C static library libsz.a
[ 69%] Built target sz
[ 70%] Building CXX object src/goesrecv/CMakeFiles/airspy_source.dir/airspy_source.cc.o
[ 70%] Linking CXX executable dcsdump
[ 70%] Built target dcsdump
[ 70%] Building CXX object src/goesrecv/CMakeFiles/rtlsdr_source.dir/rtlsdr_source.cc.o
[ 70%] Linking CXX static library libairspy_source.a
[ 70%] Built target airspy_source
[ 70%] Building CXX object src/goesrecv/CMakeFiles/nanomsg_source.dir/nanomsg_source.cc.o
[ 71%] Linking CXX static library librtlsdr_source.a
[ 71%] Built target rtlsdr_source
[ 71%] Building CXX object src/goesrecv/CMakeFiles/agc.dir/agc.cc.o
[ 72%] Linking CXX static library libnanomsg_source.a
[ 72%] Built target nanomsg_source
[ 72%] Building CXX object src/goesrecv/CMakeFiles/rrc.dir/rrc.cc.o
[ 72%] Linking CXX static library libagc.a
[ 72%] Built target agc
[ 72%] Building CXX object src/goesrecv/CMakeFiles/costas.dir/costas.cc.o
[ 73%] Linking CXX static library libcostas.a
[ 73%] Built target costas
[ 75%] Building CXX object src/goesrecv/CMakeFiles/clock_recovery.dir/clock_recovery.cc.o
[ 75%] Linking CXX static library librrc.a
[ 75%] Built target rrc
[ 76%] Building CXX object src/goesrecv/CMakeFiles/quantize.dir/quantize.cc.o
[ 76%] Linking CXX static library libclock_recovery.a
[ 76%] Built target clock_recovery
[ 77%] Building CXX object src/goespackets/CMakeFiles/goespackets.dir/goespackets.cc.o
[ 77%] Linking CXX static library libquantize.a
[ 77%] Built target quantize
[ 77%] Building CXX object src/goespackets/CMakeFiles/goespackets.dir/options.cc.o
[ 78%] Building CXX object src/decoder/CMakeFiles/compute_sync_words.dir/compute_sync_words.cc.o
[ 78%] Linking CXX executable goespackets
[ 78%] Built target goespackets
[ 78%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/correlator.cc.o
[ 79%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/derandomizer.cc.o
[ 79%] Linking CXX executable compute_sync_words
[ 79%] Built target compute_sync_words
[ 79%] Building CXX object src/assembler/CMakeFiles/assembler.dir/assembler.cc.o
[ 79%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/packetizer.cc.o
[ 80%] Building CXX object src/assembler/CMakeFiles/assembler.dir/crc.cc.o
[ 80%] Building CXX object src/assembler/CMakeFiles/assembler.dir/session_pdu.cc.o
[ 80%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/reader.cc.o
[ 82%] Building CXX object src/decoder/CMakeFiles/packetizer.dir/reed_solomon.cc.o
[ 82%] Linking CXX static library libpacketizer.a
[ 82%] Built target packetizer
[ 82%] Building CXX object src/goesrecv/CMakeFiles/benchmark.dir/benchmark.cc.o
[ 82%] Building CXX object src/assembler/CMakeFiles/assembler.dir/transport_pdu.cc.o
[ 83%] Building CXX object src/assembler/CMakeFiles/assembler.dir/virtual_channel.cc.o
[ 84%] Linking CXX executable benchmark
[ 84%] Linking CXX static library libassembler.a
[ 84%] Built target benchmark
[ 85%] Building CXX object src/decoder/CMakeFiles/packetdump.dir/packetdump.cc.o
[ 85%] Built target assembler
[ 85%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/goesrecv.cc.o
[ 85%] Linking CXX executable packetdump
[ 85%] Built target packetdump
[ 86%] Building CXX object src/goeslrit/CMakeFiles/goeslrit.dir/goeslrit.cc.o
[ 88%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/config.cc.o
[ 88%] Building CXX object src/goeslrit/CMakeFiles/goeslrit.dir/options.cc.o
[ 88%] Linking CXX executable goeslrit
[ 88%] Built target goeslrit
[ 89%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/area.cc.o
[ 89%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/config.cc.o
[ 89%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/options.cc.o
[ 90%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/decoder.cc.o
[ 90%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/demodulator.cc.o
[ 90%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/monitor.cc.o
[ 92%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/datagram_socket.cc.o
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/filename.cc.o
[ 92%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/source.cc.o
[ 92%] Linking CXX executable goesrecv
[ 92%] Built target goesrecv
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/file_writer.cc.o
[ 92%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/goesproc.cc.o
[ 94%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/gradient.cc.o
[ 94%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/handler_emwin.cc.o
[ 94%] Building CXX object src/goesproc/CMakeFiles/goesproc.dir/handler_goesn.cc.o
In file included from /home/matt/goestools/src/goesproc/map_drawer.h:5,
                 from /home/matt/goestools/src/goesproc/handler_goesn.cc:12:
/home/matt/goestools/src/goesproc/proj.h:16:10: fatal error: proj_api.h: No such file or directory
   16 | #include <proj_api.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/goesproc/CMakeFiles/goesproc.dir/build.make:174: src/goesproc/CMakeFiles/goesproc.dir/handler_goesn.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2398: src/goesproc/CMakeFiles/goesproc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
`

**Comment by kccloy** [comment]
Noted in proj.org web site under development the proj_api.h no longer exists in the newest iteration of proj.

https://proj.org/development/index.html

**Comment by mechmyday** [comment]
See this comment as a workaround https://github.com/pietern/goestools/pull/148#issuecomment-1593582659

**Comment by pietern** [comment]
This was fixed in #148 and #167. Thanks for reporting.
