### ISSUE TITLE
Cannot build with PROJ 8

### ISSUE THREAD

**Issue by nmoon88** [pietern/goestools#166]
In the newer versions of Ubuntu PROJ 6 has been replaced with PROJ 8 and despite the changes recommended in https://github.com/pietern/goestools/pull/83/files goestools will not build due to this error fatal error: proj_api.h: No such file or directory
   14 | #include <proj_api.h>
My research says that proj_api.h has been depreciated in PROJ 8 because of the same problem being encountered on other programs using the same thing.

**Comment by pietern** [comment]
This was fixed in #148 and #167. Thanks for reporting.
