### ISSUE TITLE
Goestools / Raspbian memory usage

### ISSUE THREAD

**Issue by Mopar44084** [pietern/goestools#170]
I installed Goestools on Raspbain Pc for x86, I have notice that there is a 116GB pi mailbox file in the /root/.local/share/trash.
there is a bunch of Goestools files in there also. when I try to delete this file it instantly creates it again but names it pi.2
do you know if this is part of goestools?

I don't run much on the pc as it is dedicated to goestools. 
fire data .sh
100+ python3 scripts to send images to discord

Thanks,
Christopher

**Comment by pietern** [comment]
That's not related to goestools itself. Maybe the cronjobs that run on the machine are filling up the mailbox.
