### ISSUE TITLE
True Color

### ISSUE THREAD

**Issue by njbrown09** [pietern/goestools#38]
Is it possible to get true color images from GOES-16? Something like this https://engelsjk.com/posts/goes-16-true-color-animation-using-python/images/true-color.png

**Comment by pietern** [comment]
This is not possible. The true color composite requires channels 1, 2, and 13, to my knowledge. The HRIT stream doesn't include channel 1, therefore it is not possible to create the same composite. The false color composite, which is included, is generated by composing only channels 2 and 13.
