### ISSUE TITLE
NOT ISSUE QUESTION ONLY

### ISSUE THREAD

**Issue by wds657** [pietern/goestools#60]
Hi and thank's for development this code, my question is: is possible run in windows 7 goesproc ? or how compile it, thanks !

**Comment by pietern** [comment]
Hi! I've never tried compiling on Windows. I assume there will be some issues to resolve before it works, but if there's anyone who wants to try and make it work, I'm happy to accept code changes.

For questions, also see the mailing list at https://groups.google.com/forum/#!forum/goestools-users.
