### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by doubleohwhatever** [pietern/goestools#64]
Hi All,

This past weekend I tossed together a quick web interface for GOES Tools:
https://github.com/doubleohwhatever/goes-tools-panel/

Nothing fancy and the code is a mess but it's better than nothing. I'll clean it up when I have time.

**Comment by eminence** [comment]
Cool!   This new project would probably be best shared on the [mailing list](https://groups.google.com/forum/#!forum/goestools-users).

**Comment by doubleohwhatever** [comment]
Thanks! Wasn't aware there was a mailing list. Will post there this evening.

**Comment by pietern** [comment]
@doubleohwhatever Thanks for sharing! I'm sure this will be very useful to quite a few folks!
