### ISSUE TITLE
Support for the SDRplay SDR's?

### ISSUE THREAD

**Issue by robman501a** [pietern/goestools#66]
Is there anyway I can get this to work with my SDRplay RSP2? In Linux, it does support Soapy and there is a module that is written for it. I think it's called 'SoapySDRPlay'.
Or is this tool only for the RTL dongles?

**Comment by pietern** [comment]
It currently works with the RTL dongles and the Airspy.

There is support for the HackRF in #53 and for the USRP in #72.

There is a draft pull request for Soapy support in #44, but it sounds like it's not in a working state.
