### ISSUE TITLE
Prevent goesproc file overwrite

### ISSUE THREAD

**Issue by hdoverobinson** [pietern/goestools#7]
Give a cli option to goesproc to prevent overwriting existing files in the output directory

**Comment by pietern** [comment]
Is this w.r.t. the false color file name or did you observe this elsewhere as well?

**Comment by hdoverobinson** [comment]
Separate issue - goesproc overwrites files if they already exist with the same filename in the output dir. This is convenient when testing LUT and I want to blow away existing images but there should probably be a CLI argument to allow or disallow overwrites
