### ISSUE TITLE
Build failure of goesrecv. Rpi 3B+ Ubuntu Server 18.04 64 bit

### ISSUE THREAD

**Issue by jtsfour** [pietern/goestools#75]
Building of goestools keeps failing on my Raspberry pi 3 B+ running Ubuntu Server 18.04 64 bit.

After running make the compiler hangs and crashes on.
'[90%] Building CXX object src/goesrecv/CMakeFiles/goesrecv.dir/monitor.cc.o'

Here is a pic of where the crash occurs
![Here is a pic of where the crash occurs](https://user-images.githubusercontent.com/7284318/77802802-aa482600-7049-11ea-88a9-cf2d0b28a7cd.png)

This is the first part of the cmake output
![This is the first part of the cmake output](https://user-images.githubusercontent.com/7284318/77802847-c1871380-7049-11ea-8541-1551ee36306b.png)

This is the second part of the cmake output
![This is the second part of the cmake output](https://user-images.githubusercontent.com/7284318/77802874-d19ef300-7049-11ea-9881-af0c79af7ec6.png)

If you want i can email an archive of my build directory.  Its too large for github.

I have tried rebooting.  I have also tried re-downloading and rebuilding 2-3 times. The result is always the same.  I recently built the same software yesterday on Linux Mint (on amd64 not arm) and had no notable issues.

I have been following these instructions.  https://gist.github.com/lxe/c1756ca659c3b78414149a3ea723eae2#file-goes16-rtlsdr-md

**Comment by eminence** [comment]
The `Killed (program cc1plus)` makes me think this is an out-of-memory issue, and the kernel has killed the compiler for using too much memory.  You should be able to confirm this by looking at the logs in either the command `dmesg` or in the log files in `/var/log/messages`.

**Comment by jtsfour** [comment]
@eminence Yep you are right.  The fix to this 'issue' is to run make in a single thread.  To anyone attempting to run this configuration make sure you do not use the 'j' flag for make.


Run 
make install

Not 
make -j2 install
