### ISSUE TITLE
handler_goesr.cc:138, Unhandled key in ancillary text "grid_mapping" Aborted

### ISSUE THREAD

**Issue by Boosted09Foci** [pietern/goestools#89]
Unhandled key in ancillary test "grid_mapping" causes an abort.  Anyone else having this issue?  This just popped up on me today.  Thanks!

**Comment by christheradioguy** [comment]
Having the same issue here.  Kicks in after a few seconds of running goesproc

**Comment by Boosted09Foci** [comment]
There is a closed issue on this error.  Do another clone and rebuild to use the updated script.  This will get you going again :)

**Comment by pietern** [comment]
For posterity, this was discussed in #76.
